version: '3'
services:

  personalsite:
    build:
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  portfolio:
    image: portfolio:1.0
    container_name: portfolio
    build:
      context: ./apps/portfolio
    ports:
      - 1000:80

  eight-puzzle:
    image: eight-puzzle:1.0
    container_name: eight-puzzle
    build:
      context: ./apps/eight_puzzle
    ports:
      - 2000:80

  shali_fe:
    image: shali_fe:1.0
    container_name: shali_fe
    build:
      context: ./apps/shali/shali_fe
    ports:
      - 3000:80

  postgres:
    container_name: shali_db
    image: postgres:latest
    env_file:
      - ${SHALI_BE_PATH}/.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
       - ${SHALI_BE_PATH}/shali_db/postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: shali_pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ${SHALI_BE_PATH}/.env
    # environment:
    #   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
    #   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  shali_be:
    image: shali_be:1.0
    container_name: shali_be
    build: ${SHALI_BE_PATH}/backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ${SHALI_BE_PATH}/.env
    ports:
      - 3500:7000
    volumes:
      - ${SHALI_BE_PATH}/backend/src:/shali/src
