version: '3'
services:

  shali_fe:
    image: shali_fe:1.0
    container_name: shali_fe
    build:
      context: ./shali_fe
    ports:
      - 3000:80

  postgres:
    container_name: shali_db
    image: postgres:latest
    env_file:
      - ./shali_be/.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
       - ./shali_be/shali_db/postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: shali_pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ./shali_be/.env
    # environment:
    #   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
    #   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  shali_be:
    image: shali_be:1.0
    container_name: shali_be
    build: ./shali_be/backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./shali_be/.env
    ports:
      - 3500:7000
    volumes:
      - ./shali_be/backend/src:/shali/src
