version: '3.5'

networks:
 network:
   driver: overlay 

services:
  shali_fe:
    image: shali_fe:1.0
    deploy:
      replicas: 1
    ports:
      - target: 80
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - network

  shali_postgres:
    image: postgres:latest
    env_file:
      - ./shali_be/.env
    environment:
      - POSTGRES_USER=${SHALI_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SHALI_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SHALI_POSTGRES_DB}
      - POSTGRES_SERVER=${SHALI_POSTGRES_SERVER}
    deploy:
      replicas: 1
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - ./shali_be/shali_db/postgres-data:/var/lib/postgresql/data
    networks:
      - network

  shali_pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./shali_be/.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${SHALI_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${SHALI_PGADMIN_DEFAULT_PASSWORD}
    deploy:
      replicas: 1
    ports:
      - target: 80
        published: 3501
        protocol: tcp
        mode: host
    restart: unless-stopped
    networks:
      - network

  shali_be:
    image: shali_be:1.0
    deploy:
      replicas: 1
    restart: unless-stopped
    depends_on:
      - shali_postgres
    env_file:
      - ./shali_be/.env
    ports:
      - target: 7000
        published: 3500
        protocol: tcp
        mode: host
    volumes:
      - ./shali_be/backend/src:/shali/src
    networks:
      - network
