networks:
  network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: shali_nginx
    ports:
      - 3001:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www.danilocatone.com.cer:/etc/nginx/www.danilocatone.com.cer
      - ./nginx/www.danilocatone.com.key:/etc/nginx/www.danilocatone.com.key
    depends_on:
      - shali_fe
      - shali_be
    networks:
      - network

  shali_fe:
    hostname: shali_fe
    image: shali_fe:latest
    container_name: shali_fe
    build:
      context: ./shali_fe
    ports:
      - ${SHALI_FRONTEND_PORT}:80
    networks:
      - network

  shali_postgres:
    container_name: shali_db
    image: postgres:latest
    env_file:
      - ./shali_be/.env
    environment:
      - POSTGRES_USER=${SHALI_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SHALI_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SHALI_POSTGRES_DB}
      - POSTGRES_SERVER=${SHALI_POSTGRES_SERVER}
      - POSTGRES_PORT=${SHALI_POSTGRES_PORT}
    ports:
      - "${SHALI_POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./shali_be/shali_db/postgres-data:/var/lib/postgresql/data
    networks:
      - network

        #  shali_pgadmin:
        #    container_name: shali_pgadmin
        #    image: dpage/pgadmin4:latest
        #    env_file:
        #      - ./shali_be/.env
        #    environment:
        #      - PGADMIN_DEFAULT_EMAIL=${SHALI_PGADMIN_DEFAULT_EMAIL}
        #      - PGADMIN_DEFAULT_PASSWORD=${SHALI_PGADMIN_DEFAULT_PASSWORD}
        #    ports:
        #      - "${SHALI_PGADMIN_PORT}:80"
        #    restart: unless-stopped
        #    networks:
        #      - network

  shali_be:
    hostname: shali_be
    image: shali_be:latest
    container_name: shali_be
    build: ./shali_be/backend
    restart: unless-stopped
    depends_on:
      - shali_postgres
    env_file:
      - ./shali_be/.env
    ports:
      - ${SHALI_BACKEND_PORT}:7000
    volumes:
      - ./shali_be/backend/src:/shali/src
    networks:
      - network
