networks:
  portfolio_network:
    external: true
  small_games_network:
    external: true
  shali_network:
    external: true
  sette-mezzo_network:
    external: true

services:
  personalsite:
    # image: personalsite_nginx:latest
    image: nginx:latest
    container_name: personalsite_nginx
    # build:
      # context: .
    volumes:
      - ./files/default.conf:/etc/nginx/conf.d/default.conf
      - ./files/www.danilocatone.com.cer:/etc/nginx/www.danilocatone.com.cer
      - ./files/www.danilocatone.com.key:/etc/nginx/www.danilocatone.com.key
      # - ./etc_nginx:/etc/nginx
      # - ./etc_ssl:/etc/ssl/private
      # - ./conf.d:/etc/conf.d
    # environment:
    #   - PORTFOLIO_BACKEND_PORT=1500 # ${PORTFOLIO_BACKEND_PORT}
    #   - SHALI_BACKEND_PORT=3500 # ${SHALI_BACKEND_PORT}
    ports:
      - 80:80
      # - 81:81
      - 443:443
    networks:
      - portfolio_network
      - small_games_network
      - shali_network
      - sette-mezzo_network
