version: '3.5'

networks:
  portfolio_network:
    external: true
  eight_puzzle_network:
    external: true
  shali_network:
    external: true

services:
  personalsite:
    image: personalsite-proxy:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - PORTFOLIO_BACKEND_PORT=${PORTFOLIO_BACKEND_PORT}
      - SHALI_BACKEND_PORT=${SHALI_BACKEND_PORT}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      portfolio_network:
        aliases:
          - personalsite
      eight_puzzle_network:
        aliases:
          - personalsite
      shali_network:
        aliases:
          - personalsite 
    ports:
      - "80:80"
      - "443:443"

