version: "3.8"

networks:
  network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: portfolio_nginx
    ports:
      - 1001:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www.danilocatone.com.cer:/etc/nginx/www.danilocatone.com.cer
      - ./nginx/www.danilocatone.com.key:/etc/nginx/www.danilocatone.com.key
    depends_on:
      - portfolio_fe
      - portfolio_be
    networks:
      - network

  portfolio_fe:
    hostname: portfolio_fe
    image: portfolio_fe:latest
    container_name: portfolio_fe
    build:
      context: ./portfolio_fe
    ports:
      - ${PORTFOLIO_FRONTEND_PORT}:80
    networks:
      - network

  portfolio_postgres:
    container_name: portfolio_db
    image: postgres:latest
    env_file:
      - ./portfolio_be/.env
    environment:
      - POSTGRES_USER=${PORTFOLIO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PORTFOLIO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PORTFOLIO_POSTGRES_DB}
      - POSTGRES_SERVER=${PORTFOLIO_POSTGRES_SERVER}
      - POSTGRES_PORT=${PORTFOLIO_POSTGRES_PORT}
    ports:
      - "${PORTFOLIO_POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - ./portfolio_be/portfolio_db/postgres-data:/var/lib/postgresql/data
    networks:
      - network

        #  portfolio_pgadmin:
        #    container_name: portfolio_pgadmin
        #    image: dpage/pgadmin4:latest
        #    env_file:
        #      - ./portfolio_be/.env
        #    environment:
        #      - PGADMIN_DEFAULT_EMAIL=${PORTFOLIO_PGADMIN_DEFAULT_EMAIL}
        #      - PGADMIN_DEFAULT_PASSWORD=${PORTFOLIO_PGADMIN_DEFAULT_PASSWORD}
        #    ports:
        #      - "${PORTFOLIO_PGADMIN_PORT}:80"
        #    restart: always
        #    networks:
        #      - network

  portfolio_be:
    hostname: portfolio_be
    image: portfolio_be:latest
    container_name: portfolio_be
    build: ./portfolio_be/backend
    restart: always
    depends_on:
      - portfolio_postgres
    env_file:
      - ./portfolio_be/.env
    ports:
      - ${PORTFOLIO_BACKEND_PORT}:7000
    volumes:
      - ./portfolio_be/backend/src:/portfolio/src
    networks:
      - network
