version: '3.5'

networks:
  network:
    driver: overlay 

services:
  portfolio_fe:
    image: portfolio_fe:1.0
    deploy:
      replicas: 1
    ports:
      - "${PORTFOLIO_FRONTEND_PORT}:80"
    networks:
      - network

  portfolio_postgres:
    image: postgres:latest
    env_file:
      - ./portfolio_be/.env
    environment:
      - POSTGRES_USER=${PORTFOLIO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PORTFOLIO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PORTFOLIO_POSTGRES_DB}
      - POSTGRES_SERVER=${PORTFOLIO_POSTGRES_SERVER}
      - POSTGRES_PORT=${PORTFOLIO_POSTGRES_PORT}
    deploy:
      replicas: 1
    ports:
      - ${PORTFOLIO_POSTGRES_PORT}:5432
    restart: always
    volumes:
      - ./portfolio_be/portfolio_db/postgres-data:/var/lib/postgresql/data
    networks:
      - network

  portfolio_pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./portfolio_be/.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PORTFOLIO_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PORTFOLIO_PGADMIN_DEFAULT_PASSWORD}
    deploy:
      replicas: 1
    ports:
      - ${PORTFOLIO_PGADMIN_PORT}:80
    restart: always
    networks:
      - network

  portfolio_be:
    image: portfolio_be:1.0
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - portfolio_postgres
    env_file:
      - ./portfolio_be/.env
    ports:
      - ${PORTFOLIO_BACKEND_PORT}:7000
    volumes:
      - ./portfolio_be/backend/src:/portfolio/src
    networks:
      - network
